### ISSUE TITLE
Itens don't drop when broken

### ISSUE THREAD

**Issue by morottao** [HeyItsMeNobody/karam#3]
Log: https://paste.ee/p/XywXT

**Comment by HeyItsMeNobody** [comment]
Hello @morottao ! It seems like there’s a lot of things broken like the LAN screen and there’s also a lot of outdated mods. Could you try the mod on its own with Fabric API for me?

**Comment by HeyItsMeNobody** [comment]
Closing this as there has been no response for a while.
